### PR TITLE
responsive login page fix resolves #3

### LINKED ISSUE #3: the login/signup page is not responsive
i'll fix the responsiveness of the login page
currently looks like this :
image

### PR DESCRIPTION
**Pull request by Saurav-Singh-Rauthan**

### CODE REVIEW

**Comment by Saurav-Singh-Rauthan** [comment]
@ArpitPy have a look

**Comment by ArpitPy** [comment]
@Saurav-Singh-Rauthan You changed the version of react-router to v6 that will probably break the App.js since it does not support Redirect and other syntax of v5

**Comment by Saurav-Singh-Rauthan** [comment]
ok I'll downgrade to v5

**Comment by Saurav-Singh-Rauthan** [comment]
done @ArpitPy

**Review by ArpitPy — APPROVED** [review]

**Pull request merged**
